### ISSUE TITLE
Allow using bigger decks

### ISSUE THREAD

**Issue by glowacki-dev** [mavend/octoboard#112]
I've generated decks of multiple sizes in #103. Current default is the one with 8 symbols and 57 total cards.

More cards need more symbols on a card, but may be useful for games with more players.

This will also require changing layouts so they can be adapted to more and less symbols

**Comment by Bombasarkadian** [comment]
6 symbols is Dobble Junior, so we can use it as "easy" mode. We can also do something like 9 or 10 for "hard" (10 is probably really hard already) and it should be enough
