### ISSUE TITLE
Game screen reloads after writing messages

### ISSUE THREAD

**Issue by glowacki-dev** [mavend/octoboard#118]
On Chrome and Safari, when writing any message in kalambury game screen reloads after each sent message

**Comment by Bombasarkadian** [comment]
Fixed in https://github.com/mavend/octoboard/commit/f6ab701a936d7b1f6a6f9d3a040eaf110379da6b

**Comment by glowacki-dev** [comment]
It's back on latest version. Happens when running in Edge
