### ISSUE TITLE
Show which picture was matched

### ISSUE THREAD

**Issue by Bombasarkadian** [mavend/octoboard#128]
We can either show it in sidebar or maybe highlight the matched picture. In an in-real-life version of the game you always know this, because the other player has to say it

**Comment by pastDexter** [comment]
But everyone has different matching picture, so it is not really important for other players to know

**Comment by Bombasarkadian** [comment]
Sometimes it makes it easier to play the next card when you're stuck and cards are changing quickly. You already know all the pictures you have so you're basically waiting for anyone to play one of your pictures

**Comment by Bombasarkadian** [comment]
But it should be enough to show those pictures in a sidebar
