### ISSUE TITLE
Pictures preloading not working

### ISSUE THREAD

**Issue by glowacki-dev** [mavend/octoboard#204]
Pictures doesn't seem to be preloaded, so they appear with delay after the card is first displayed making it easy to see which pictures are new ones. It used to work properly as far as I remember

**Comment by glowacki-dev** [comment]
It seems like there is a request made for each picture and browser (Edge) waits for 304 response to show cached image - some requests finish faster than others. We should somehow avoid fetching the image and force using preloaded versions

**Comment by glowacki-dev** [comment]
This is most likely the issue:
`A 'cache-control' header contains directives which are not recommended: 'must-revalidate'`

**Comment by pastpatryk** [comment]
@glowacki-dev https://docs.netlify.com/routing/headers/#syntax-for-the-headers-file
