### ISSUE TITLE
Lobby filtering

### ISSUE THREAD

**Issue by glowacki-dev** [mavend/octoboard#21]
Add some basic filters for lobby:
1. hide full rooms
2. hide rooms with started game

That's really all we need now 😃

**Comment by Bombasarkadian** [comment]
We can make it future-proof by also filtering based on lobby language. Sometime in the future we may add phrases that are in languages other than polish 🤔

**Comment by pastpatryk** [comment]
Design concept from @glowacki-dev :
![image](https://user-images.githubusercontent.com/1544476/111769983-24e90180-88aa-11eb-86ef-1355ece18df9.png)
