### ISSUE TITLE
Add persistent data store

### ISSUE THREAD

**Issue by pastpatryk** [mavend/octoboard#39]
Currently all games are saved in-memory on server side, so after every deploy or restart everything disappear. We should one of the provided MongoDB or Firebase connectors

**Comment by pastDexter** [comment]
It looks like Mongo is no longer supported https://boardgame.io/documentation/#/storage

**Comment by pastDexter** [comment]
We can use FlatFile or Firebase

**Comment by Bombasarkadian** [comment]
Flatfile on heroku is also not an option
