### ISSUE TITLE
Find more appealing name than "Corona Games" 😷

### ISSUE THREAD

**Issue by pastDexter** [mavend/octoboard#58]

**Comment by turbaszek** [comment]
sketzchen, sketchly, sketch space, Sketchegy, Sketchlux, Drawomatic, Drawology, Drawdeck, Drawhunt, Drawado 🤷🏼‍♂️

**Comment by Bombasarkadian** [comment]
We need something more generic. I hope we'll have many other games as well

**Comment by pastDexter** [comment]
yes, we definitely want more games in the future

**Comment by turbaszek** [comment]
gamed

**Comment by Bombasarkadian** [comment]
![Screenshot 2020-03-31 at 13 24 48](https://user-images.githubusercontent.com/2972266/78021139-00231380-7353-11ea-97fd-b7eff2014f42.png)
Has some scam-like feel to it, doesn't it? 👮‍♀
