### ISSUE TITLE
[Airbrake] [Production] The project's quota for this operation has been exceeded.

### ISSUE THREAD

**Issue by pastDexter** [mavend/octoboard#87]
**Airbrake error:** [#0254](https://pas-patryk-gmail-com.airbrake.io/projects/265788/groups/2716820982301180254)
**Airbrake project:** corona-games

**Error type:** `Error`
**Error message:** `` The project's quota for this operation has been exceeded. ``
**Where:** `<no information>`
**Occurred at:** Apr 06, 2020 11:58:15 UTC
**First seen at:** Apr 06, 2020 11:58:15 UTC
**Occurrences:** 0 (0 since last deploy on `<no information>`)
**Severity:** `error`

**URL:** [https://corona-games.netlify.com/login/guest](https://corona-games.netlify.com/login/guest)
**File:** `https://corona-games.netlify.com/src/notifier.ts`

**Backtrace:**
```
https://corona-games.netlify.com/src/notifier.ts:106:in 
https://corona-games.netlify.com/src/notifier.ts:153:in notify
https://corona-games.netlify.com/src/notifier.ts:67:in apply
```

**Comment by Bombasarkadian** [comment]
We should be ok for now after changes in #97, right? @pastDexter

**Comment by pastDexter** [comment]
yep
